# _config.yml - GitHub Pages with Jekyll

title: Peter Korman -  SOC / Blue Team Analyst
description: Portfolio of hands-on labs (TryHackMe, Splunk) and SOC Level 1 path progress.
baseurl: "/portfolio-soc-blue-team"  # ← TOHLE JE KLÍČOVÉ!
#baseurl: ""  # ← TOHLE JE KLÍČOVÉ!
url: "https://peterkor.github.io"

# Jekyll theme (GitHub Pages supported)
theme: jekyll-theme-hacker

# Plugins (GitHub Pages default)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown engine
#markdown: kramdown

# Permalink structure
#permalink: /:title/

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
